### ISSUE TITLE
Executable binary doesn't work anymore

### ISSUE THREAD

**Issue by JammingBen** [RSeidelsohn/license-checker-rseidelsohn#118]
Starting with version `v4.3.1`, `bin/license-checker-rseidelsohn` has been renamed to `bin/license-checker-rseidelsohn.js`. However, the change is not being reflected in the [package.json](https://github.com/RSeidelsohn/license-checker-rseidelsohn/blob/master/package.json#L23) file, leading to the executable not working.

**Comment by FrankVerbeek** [comment]
To expand on the issue, this also breaks running the command via npx:

`'license-checker-rseidelsohn' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by MelanieW97** [comment]
Exactly, the command "npx license-checker-rseidelsohn" in unusable right now.
Look forward to getting the fix.

And thank you for this great package!
