### ISSUE TITLE
Output plain vertical format

### ISSUE THREAD

**Issue by johnthagen** [RSeidelsohn/license-checker-rseidelsohn#2]
Angular CLI provides a nice format for displaying all license files for each respective package. Would you consider adding such a format to this fork of `license-checker`? It makes for a more cleaner look when embedding within an application.

Here is an example of the format: https://angular.io/3rdpartylicenses.txt

**Comment by RSeidelsohn** [comment]
Hi @johnthagen ,

sorry for the totally late reply. I just recently noticed that this fork of the license-checker actually has been noticed by other users. I am happy to take care of your request. Anyway, plase be aware that I have a full time job and two little children and hobbies (one of which is coding), so caring for the license checker is not my top priority. Nevertheless I am happy to help other people with this project and will now start having a look into your request.

Cheers, Roman.

**Comment by johnthagen** [comment]
> Anyway, plase be aware that I have a full time job and two little children and hobbies (one of which is coding), so caring for the license checker is not my top priority.

Totally understand! Just wanted to get this request in in case others might benefit as well. No pressure from me. 😄 Thanks!

**Comment by RSeidelsohn** [comment]
Dear @johnthagen ,

could you possibly check clone the repo https://github.com/RSeidelsohn/license-checker-rseidelsohn/tree/feature/0002_create-plain-vertical-output locally and try the command `node bin/license-checker-rseidelsohn --plainVertical` in it's root directory and tell me whether this is the format you want? If so, I will refine it a bit, update the documentation and then merge it.

Cheers, Roman.

**Comment by RSeidelsohn** [comment]
Oh right, this should look different. I'll take care of this, though probably not today. Thanks a lot for having a look into the branch!

**Comment by RSeidelsohn** [comment]
Ok, I just had a look again an know what's going on. The example output from `Angular CLI` you sent me a link from, doesn't show the version numbers. So I guess it only outputs the direct dependencies. `license-checker` by default outputs all dependencies - I just stripped the version numbers in order to make it look like the example you showed to me. So what looks like duplicates in fact are license infos of different versions of the same modules. Nested dependencies. If you add the `--direct` option, you will see no duplicates. So the questions remains how I should deal with this problem. Should I add version numbers per default or append the `--direct` option per default? Would it make sense to call the option implemented here `--angularCliStyle` and only output the direct dependencies? What do you think? Unfortunately, what initially looks simple, is a bit more complicated when it comes to implementation.

Cheers, Roman.

**Comment by johnthagen** [comment]
@RSeidelsohn Interesting observations!

I didn't even realize until you pointed it out that Angular CLI is missing version numbers. I think this is an important piece of information to trace back to exact project versions.

I would propose doing something like:

```
log-symbols 0.10.0
MIT
MIT License

Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)
...

log-symbols 0.11.0
MIT
MIT License

Copyright (c) Sindre Sorhus <sindresorhus@gmail.com> (sindresorhus.com)
...
```

Where we put the version right after the package name, separated by a single space. That way, we look just like Angular CLI, but we also don't lose the extra version information.

Also, I'm pretty sure Angular CLI is showing nested dependencies (they are just as important for license information) but perhaps they are de-duplicating and stripping versions off.

I propose that we show all dependencies, even nested. If we put the version numbers on, then it's super clear to anyone that multiple versions of the same package are being used. This also matches, like you say, how the rest of this tool works by default.

> Should I add version numbers per default or append the --direct option per default?

I would recommend adding version numbers by default. Being explicit seems better here and matches other such license tools I've seen (for example, `pip-licenses` from Python).

**Comment by RSeidelsohn** [comment]
Should be done now. I increased the version number to `1.2.0` and added an alias for the `--plainVertical` option called `--angularCli`.

**Comment by johnthagen** [comment]
I should be able to check this out on Saturday and get back to you. Thanks.

**Comment by johnthagen** [comment]
@RSeidelsohn I tried this out and it worked great! To me, this looks complete. Thanks!

**Comment by johnthagen** [comment]
@RSeidelsohn Could you please publish this to `npm` so we can try out in some production environments? Thanks!

**Comment by RSeidelsohn** [comment]
Hi John,

wow, I really forgot about that step. Sorry about that. I took the chance to fix a bug I found with white/blacklisting for package names starting with '@' and updated all dependencies to their latest versions as well. The current version is now at 1.2.1.

So I hope you will find the new version on npmjs useful for your project(s)! Please tell me whenever you miss a feature or find a bug!

Cheers, Roman.

**Comment by johnthagen** [comment]
Just tried it out, and it looks great. Thanks!
