### ISSUE TITLE
Provide typings

### ISSUE THREAD

**Issue by arsinclair** [RSeidelsohn/license-checker-rseidelsohn#21]
`npm i --save-dev @types/license-checker-rseidelsohn` produces

> An unexpected error occurred: "https://registry.yarnpkg.com/@types%2flicense-checker-rseidelsohn: Not found".

Types were available before it was forked (`@types/license-checker`), so maybe they can be forked as well without any major changes.

**Comment by RSeidelsohn** [comment]
Hi @arsinclair , great idea! I didn't think of this yet. I'll do my best trying to implement this the upcoming week!

Cheers, Roman.
