### ISSUE TITLE
How to get all non-dev dependencies?

### ISSUE THREAD

**Issue by rhegner** [RSeidelsohn/license-checker-rseidelsohn#24]
I'd like to get all non-dev dependencies, including indirect dependencies. I tried using the `production` flag, but then I see only the direct dependencies:

```
const checker = require('license-checker-rseidelsohn');

checker.init(
{
    start: 'C:/Robert/VRM/inventory-system/CustomerPortal',
    production: true
},
(err, packages) => 
{
    if (err) {
        console.error(err);
    } else {
        console.log(packages);
    }
}
);
```

How can include the non-direct non-dev dependencies too?

**Comment by RSeidelsohn** [comment]
Hi @rhegner,

sorry for the totally late reply. I am in vacation now and this is when I find some time for caring about this project. Did you try any of the recent versions? I recommend you give the current v3.0.1 a try. When I run it locally, I get the results I expect with the `--production` flag.

**Comment by codeability-ab** [comment]
Hello!
Here's a late response...

When I run the command with `--production` i still see all (or many) devDependencies (on Mac and Windows).

If I run the command in Linux (RHEL7 in podman in a TeamCity server) I only see direct dependencies including devDependencies.

The Linux thing is weird.

About the devDependencies showing - could it be some transitive dependency "opening up a leak into devDeps" by accidentally listing a devDep as a dep?

/johan

**Comment by RSeidelsohn** [comment]
Hello @codeability-ab,

it's been a long time, but now I take care more often and wanted to tackle your issue, but I can't see a problem - at least with version `4.2.3`. When I use `--production` in combination with `--direct true`, then I see just the production `dependencies` listed. When I leave the `--direct` option off, I see more `dependencies`, of course, but in my case none of them are part of the `devDependencies`. But this is a pure coincidence - of course the ' devDependencies'  of the project examined can as well be indirect dependencies of the preoduction `dependencies`.

Should you still see a problem here, then please let me know. For now, I'll close this issue.
