### ISSUE TITLE
support exclude @scope?

### ISSUE THREAD

**Issue by linqunhe** [RSeidelsohn/license-checker-rseidelsohn#27]
such as @babel/*;

thanks

source project have pr: https://github.com/davglass/license-checker/pull/219

**Comment by Undistraction** [comment]
Yes. This would be really helpful. We have a slightly different usecase. We are publishing packages from a Lerna monorepo. We then consume these packages in our frontends. Our packages have `license: "UNLICENSED"` in their `package.json`s. On CI we could just add `UNLICENSED` to `--failOn`, however that would mean we would miss other packages that were unlicenced. If we don't add it `--failOn`, our own packages will cause fails. Our only options then are to either manually add and maintain all our namespaced packages (50+) to the `--excludePackages` flag or write something to parse a list of all our packages out of the project's `package.son`. It would be much cleaner to be able to do `--excludeNamespace @example`.

**Comment by RSeidelsohn** [comment]
Hi @linqunhe and @Undistraction,

it took a looong time, but now my new employer allows me to work on this project every 2nd friday, so things finally might come up to speed here. I'll have a look into this, as it definitely is a nice and missing feature, if not even a bug.

**Comment by RSeidelsohn** [comment]
Hello again, @linqunhe and @Undistraction,

you can achieve what you need with the `--excludePackageStartingWith` option, e.g.

```bash
node ./bin/license-checker-rseidelsohn --excludePackagesStartingWith @babel
```

This skips all packages from the `@babel` scope.
