### ISSUE TITLE
MIT for package husky

### ISSUE THREAD

**Issue by gugu** [RSeidelsohn/license-checker-rseidelsohn#3]
```
❯ npx license-checker-rseidelsohn --onlyAllow="Unlicense;MIT;ISC;Apache-2.0;BSD;MPL;CC;Custom: http://github.com/dscape/statsd-parser;WTFPL" --includePackages=husky --direct
npx: installed 59 in 8.062s
   ├─ licenses: MIT*
   ├─ repository: https://github.com/typicode/husky
   ├─ publisher: Typicode
   ├─ email: typicode@gmail.com
   ├─ path: C:\Users\andre\Documents\GitHub\front-settings\node_modules\husky
   └─ licenseFile: C:\Users\andre\Documents\GitHub\front-settings\node_modules\husky\LICENSE
```

The LICENSE file:

```
License Zero Parity 7.0.0 (see LICENSE-PARITY file) and MIT (contributions, see LICENSE-MIT file) with exception License Zero Patron 1.0.0 (see LICENSE-PATRON file)
```

It needs to be License Zero Parity for this module

**Comment by Ephigenia** [comment]
Just in case, there’s the merge-request opened by @gugu: https://github.com/RSeidelsohn/license-checker-rseidelsohn/pull/4

**Comment by RSeidelsohn** [comment]
Indeed, thanks for filing this issue and for mentioning the merge request - and thanks to @gugu ! This should be fixed now.
I am really sorry this took so long - I was not aware of the fact that this repository is actually in use by other people! I think I'll care more and more often in the future.
