### ISSUE TITLE
The direct option, when using the `init` api seems to be backward

### ISSUE THREAD

**Issue by eamodio** [RSeidelsohn/license-checker-rseidelsohn#35]
The typings seem to say it's a `boolean` but the code seems to check for `=== 0`. Which also seems backwards -- since setting `direct` to `0` enables direct dependency only output.

**Comment by twastvedt** [comment]
I believe that currently the direct option is actually used as the depth of searching. So a depth of 0 gets just the top level, and `undefined` (or `Infinity`, which is what is used if `direct` isn't set), walks the entire tree.

**Comment by twastvedt** [comment]
The option gets translated here for the cli, but the api doesn't have this conversion done:
https://github.com/RSeidelsohn/license-checker-rseidelsohn/blob/17bf4d3eafbb9b14304a9d2bbbb671784ac4a11b/lib/args.js#L80-L84
