### ISSUE TITLE
Direct production dependencies expects devDependencies to exist

### ISSUE THREAD

**Issue by Coada** [RSeidelsohn/license-checker-rseidelsohn#38]
Hello Roman,

Thank you for taking the time to create and maintain this project.

I've observed that running your script combined with `--production --direct` will fail for a project who's `package.json` file does not contain `devDependencies`:

```
node_modules/license-checker-rseidelsohn/lib/index.js:300
            const devDependencies = Object.keys(json.devDependencies);
                                           ^

TypeError: Cannot convert undefined or null to object
```

It can be prevented by adding `devDependencies: {},` to the package file, but perhaps it could be good to assume that not all package files have this dependency type.

Thanks!

**Comment by RSeidelsohn** [comment]
Thanks a lot for the issue, @Coada. It's been a while, but now this is fixed in Release `4.2.5`.
