### ISSUE TITLE
Markdown format is using incorrect line breaks

### ISSUE THREAD

**Issue by slhck** [RSeidelsohn/license-checker-rseidelsohn#43]
Thanks for maintaining this useful fork.

I noted that the Markdown output format is not according to spec. It outputs lines like:

```markdown
[@cspotcode/source-map-consumer@0.8.0](https://github.com/cspotcode/source-map) - BSD-3-Clause
[@cspotcode/source-map-support@0.7.0](https://github.com/cspotcode/node-source-map-support) - MIT
[@expo/spawn-async@1.6.0](https://github.com/expo/spawn-async) - MIT
```

Note that in Markdown (whether adhering to John Gruber's original syntax or [GitHub Flavored Markdown](https://github.github.com/gfm/#paragraph)), the above lines are not considered a list, and you cannot guarantee that this produces a line break after every line. It really depends on the parser. Some editors render it correctly (including GitHub's own editor), others don't (e.g. Visual Studio Code).

Hence, it would be preferale to add two spaces to the end of each line to force a manual line break:

```markdown
[@cspotcode/source-map-consumer@0.8.0](https://github.com/cspotcode/source-map) - BSD-3-Clause  
[@cspotcode/source-map-support@0.7.0](https://github.com/cspotcode/node-source-map-support) - MIT  
[@expo/spawn-async@1.6.0](https://github.com/expo/spawn-async) - MIT  
```

Alternatively, one could output an actual list:

```markdown
- [@cspotcode/source-map-consumer@0.8.0](https://github.com/cspotcode/source-map) - BSD-3-Clause
- [@cspotcode/source-map-support@0.7.0](https://github.com/cspotcode/node-source-map-support) - MIT
- [@expo/spawn-async@1.6.0](https://github.com/expo/spawn-async) - MIT
```

Both would ensure universally correct Markdown rendering.

Which one do you prefer? I can provide a PR for that.

**Comment by slhck** [comment]
Any thoughts, @RSeidelsohn?

**Comment by RSeidelsohn** [comment]
Hi @slhck , thanks for bumping this issue up. In fact, if you could provide a PR for that, that would be awesome.
