### ISSUE TITLE
Issues with NPM 9 

### ISSUE THREAD

**Issue by aaschlote** [RSeidelsohn/license-checker-rseidelsohn#54]
Hello all,

I'm facing some issues to install the ``license-checker-rseidelsohn`` due my CI/CD environment is current using the npm 9. Any reason we don't allow this version? I have seen this restriction was added recently.

![image](https://user-images.githubusercontent.com/11893663/214013998-d90d1661-7241-4a59-90aa-5edcc4018f94.png)

**Comment by slhck** [comment]
I think you should file a PR that bumps this line:

```
"npm": "^8",
```

in the package.json to use `>=8`.

**Comment by firecow** [comment]
I agree a `>=8` if this application actually supports npm versions above 8

**Comment by sebastianrothe** [comment]
My CI pipeline fails because of the restriction :(

**Comment by RSeidelsohn** [comment]
Sorry guys, this was my fault. There was no reason whatsoever to limit npm major versions to 8. I now fixed this in release `4.1.0`.

**Comment by aaschlote** [comment]
It's working again, thanks for the fix!
