### ISSUE TITLE
Dependencies deprecated

### ISSUE THREAD

**Issue by mojiAh** [RSeidelsohn/license-checker-rseidelsohn#67]
`npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs`

> npm ls readdir-scoped-modules
> myrepo
> └─┬ license-checker-rseidelsohn@4.1.1
>       └─┬ read-installed-packages@1.0.0
>            └── readdir-scoped-modules@1.1.0

**Comment by Semigradsky** [comment]
I see. Will try to move from `readdir-scoped-modules` to `@npmcli/fs`

**Comment by Semigradsky** [comment]
@RSeidelsohn please try `read-installed-packages`@2.0.0
