### ISSUE TITLE
Pass relative path to start

### ISSUE THREAD

**Issue by punowo** [RSeidelsohn/license-checker-rseidelsohn#68]
Hi. I'm trying to write a small wrapper around this library with the end purpose of generating readmes. 
```javascript
const path = require("path");
const licenceChecker = require("license-checker-rseidelsohn");

/**
 *
 * @param {String} typeOfPackage
 * @param {String} toBeCheckedLocalPackage
 */
const checkLicences = (typeOfPackage, toBeCheckedLocalPackage) => {
  let typeOfPackagePath;
  if (!["library", "service"].includes(typeOfPackage)) {
    throw new Error("Please use 'library' or 'service' when calling");
  } else {
    typeOfPackagePath = typeOfPackage === "library" ? "libraries" : "services";
  }
  const globalPath = path.join(__dirname, "..", "..");
  console.log(globalPath);
  const toBeCheckedLocalPackagePath = (path.join(
    globalPath,
    typeOfPackagePath,
    toBeCheckedLocalPackage,
  ));
    const rel = path.relative(__dirname, toBeCheckedLocalPackagePath)
    console.log(rel);

  console.log(toBeCheckedLocalPackagePath);

  licenceChecker.init(
    { start: '../../logger' },
    function (err, packages) {
      if (err) {
        console.error(err);
      } else {
        console.dir(packages);
      }
    }
  );
};

checkLicences("library", "logger")
```
The file structure is something like this: 
![Screenshot_1](https://user-images.githubusercontent.com/96526435/222697465-fe738217-3bd1-4fbb-bf40-727f4c1a45ff.png)

No matter what I pass to start, it worn't work. `Error: No packages found in this path...`. Changing the directory and then running `licence-checker-rseidelsohn` will work without any problems.

Is this a bug ? How should I approach this ? Pasing `./` works, for example.

**Comment by matheuspl** [comment]
Having the same issue here

**Comment by matheuspl** [comment]
I have the same issue. 
Using the absolute dir path and path.join solved for me.
Try this approach on the start script:
`path.join(__dirname, '..', '..', 'logger')`

**Comment by RSeidelsohn** [comment]
Hello @punowo,

sorry for the loooong time it took me to tackle this issue. I just tried it on my (Ubuntu) system, and using a relative value for `--start` going to a sibling directory (`--start ../shortly`) worked just fine. It might be due to changes and fixes I did in the meantime - the current version I checked this in is `v4.2.3`. Please tell me if this is still an issue for you.

Cheers, Roman.

**Comment by punowo** [comment]
> Hello @punowo,
> 
> sorry for the loooong time it took me to tackle this issue. I just tried it on my (Ubuntu) system, and using a relative value for `--start` going to a sibling directory (`--start ../shortly`) worked just fine. It might be due to changes and fixes I did in the meantime - the current version I checked this in is `v4.2.3`. Please tell me if this is still an issue for you.
> 
> Cheers, Roman.

Hi. Thanks for looking at this. I'll try and recreate the issue asap and report back. In the end I just ended up calling `license-checker-rseidelsohn` in a shell script. Please feel free to close this if you don't see a response from me in the next few days because I might get overwhelmed by other things.
