### ISSUE TITLE
Why this library weights 127MB?

### ISSUE THREAD

**Issue by kamilluc** [RSeidelsohn/license-checker-rseidelsohn#89]
I belive that we don't need 125MB additional modules inside test folder. Would it be possible to remove it from package and leave only in GitHub or remove entierly?

**Comment by RSeidelsohn** [comment]
Dear @kamilluc,

thanks for bringing this up. These modules were in the project already when I took it over, and the tests are a huge painpoint for me - I'd love to replace them with jest tests completely.
That being said, I'll try to find a way to get rid of these. Indeed, it doesn't make any sense to transfer these modules when you just want to use the license checker.
