### ISSUE TITLE
Typos in CLI arguments are silently ignored

### ISSUE THREAD

**Issue by johnthagen** [RSeidelsohn/license-checker-rseidelsohn#9]
If you pass an invalid CLI argument, it is silently ignored rather than showing an error and stopping:

```bash
$ license-checker-rseidelsohn --BATMAN
# This completes successfully
```

What this means is that if the user has a subtle typo in their arguments, they may not realize certain features aren't enabled.

**Comment by RSeidelsohn** [comment]
Oh, right. This is a UX bug, I'd say. Thanks for reporting this. I will take care of this as soon as possible - hopefully during the upcoming weekend. I will keep you posted.

**Comment by RSeidelsohn** [comment]
Sorry, @johnthagen, I totally forgot about license-checker last weekend. But I added the feature you have been asking for (and updated the node dependencies to their latest versions alongside) in the new version `1.2.2`. I hope it fits your needs. One thing to mention: It only checks for unknown arguments passed with one or two leading dashes `-`, as options need this prefix.

Cheers, Roman.

**Comment by RSeidelsohn** [comment]
Hi @johnthagen , I will wait another 1-2 weeks and the close this issue if you don't tell me anything different.

**Comment by johnthagen** [comment]
@RSeidelsohn Sorry for the delay. I tried out 1.2.2 and see that it prints a warning now. That should solve the case. Is there a reason why the tool continues to output even with invalid entries? Most tools I've seen if they get an invalid input like that would show the warning and then abort, otherwise a user could miss the warning in a CI log, or if the terminal fills up with output.

**Comment by RSeidelsohn** [comment]
Hm, that's a good question. First of all, thank you for checking this again.
The fact that the tool runs despite the warning is that I think a `warning` is not enough to stop the tool from running. If it should stop the tool, then the warning should in fact be an error.
I guess I need some time to think this through - what you say here totally makes sense.

**Comment by RSeidelsohn** [comment]
Hi @johnthagen, I finally made unknown options to be treated as an error, exiting the program with error code '1'. Sind this is a potentially breaking change, I updated the major version number - we now go with v2.0.0.
