### ISSUE TITLE
--direct doesn't support any number input

### ISSUE THREAD

**Issue by zola-25** [RSeidelsohn/license-checker-rseidelsohn#92]
Hey, love the tool, I've got a lot of use out of it already.

I've found one issue though, I can't seem to get the --direct parameter to work in any way except as a flag.

I'm on windows, I've tried both calling license-checker-rseidelsohn directly and through the .ps1 script, but I have no joy with specifying the depth level, so I'm forced to either output every dependency, or the top level ones in my package.json.

license-checker-rseidelsohn.ps1  --direct 9 
license-checker-rseidelsohn.ps1  --direct "9" 
license-checker-rseidelsohn.ps1  --direct 99
license-checker-rseidelsohn.ps1  --direct 0 
license-checker-rseidelsohn.ps1  --direct='99'

..all produce the same number of packages.

Am I calling it wrong? 

I'm not hot on JS/TS but I did look around the source code, I don't know if this Type definition being set as Boolean is the problem:

[knownOptions in args.js](https://github.com/RSeidelsohn/license-checker-rseidelsohn/blob/0be3cc25b5aa338e86d4151c29688de2170225c2/lib/args.js#L18)

I tried digging a bit further but I got a bit lost in the argument parsing. 

Has this --direct [number] feature worked before? Or maybe it works on different setups?

**Comment by RSeidelsohn** [comment]
Hi @zola-25, I can't remember how the code dealt with this parameter originally, but now it internally uses a number for that parameter.
`true` will be converted into `0`, `false`, any value that is not a number or no value at all will be converted into `Infinity`, and if you pass a number, it'll use that number.
From my tests I made back when I refactored that piece of code I am pretty sure that it works fine under Linux. So it might be an issue related to Windows. Could you maybe try to run your code in the Windows subsystem for Linux (WSL) and see if that makes any difference?

**Comment by RSeidelsohn** [comment]
Oh no, I just tested it myself and I can confirm that it is broken! I'll try to fix it asap.

**Comment by RSeidelsohn** [comment]
Hi @zola-25, this bug is fixed now. I wonder for how long this did not work... But now it's fine.

Now, the `--direct` (which should rather be `--depth`) option works as follows:

- Passing in no value or leaving the parameter off will be interpreted as Infinity
- Passing in true will be interpreted as Infinity
- Passing in false will be interpreted as 0
- Passing in a number will be interpreted as that number
- Passing in any other value that can't be recognized as a number will be interpreted as Infinity

**Comment by zola-25** [comment]
Hi @RSeidelsohn, sorry it's taken me so long to thank you for fixing this. 

The tool has been most useful to add credit and license info of the third-party packages used in my application.

In the end I decided just obtain the license information for my direct dependencies anyway, rather than diving too deep into the node package ecosystem of who-knows-what. 

I'll certainly be using this tool again at some point so a huge thanks for continuing to maintain it. 

👍👍👍

**Comment by ssmirr** [comment]
> Now, the --direct (which should rather be --depth) option works as follows:
> Passing in no value or leaving the parameter off will be interpreted as Infinity
> Passing in true will be interpreted as Infinity
> Passing in false will be interpreted as 0
> Passing in a number will be interpreted as that number
> Passing in any other value that can't be recognized as a number will be interpreted as Infinity

Thanks for fixing this @RSeidelsohn! but I think the logic here may not be exactly what a user expects 👇 

_The options make sense except, `direct=true` should be interpreted as 0 not infinity. And false should be interpreted as infinity not 0. Additionally no value if `--direct` is specified should be interpreted as 0._ 

`direct` means direct dependencies listed in the package.json so depth is 0. Or am I misunderstanding the description of `direct` option?

**Comment by zola-25** [comment]
Just a thought - this might be because I think there was or is an intention for this flag to actually be named --depth.

So --depth=false kind of makes sense semantically, i.e. just the direct dependencies (level zero).

And --depth=true means go down to the lowest level.

**Comment by ssmirr** [comment]
@zola-25 thank you for sharing more context! Yes I agree if the option is renamed to `--depth` that logic would make sense. Sounds like keeping it as alias wouldn't work either, as the logic for `--depth` and `--direct` would be different. 

Wondering if I should open a new issue for this so it doesn't get forgotten to track?
